apply plugin: 'com.android.application'

// Load keystore
def keystorePropertiesFile = rootProject.file("signingConfigs.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    signingConfigs {
        wsjtx_monitor_signing {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    //compileSdkVersion 33      beginning with SDK 33 use compileSdk (instead of compileSdkVersion) and place it in the defaultConfig block
    defaultConfig {
        applicationId "com.feotec.wsjt_xmonitor"
        compileSdk 36
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 66
        versionName "2.104"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resValue  'bool', 'multicastIP', 'false'         //  To enable/disable MUST MANUALLY add/remove permissions CHANGE_WIFI_STATE and CHANGE_WIFI_MULTICAST_STATE
                                                        //  from manifest.xml.  And, obviously, change this constant to false.
    }
    String buildString = 'Monitor'
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.wsjtx_monitor_signing
        }
        debug {
            debuggable true
            applicationIdSuffix ".debug"
            //buildString = 'Debug'     //  remove when building release, restore while debugging.
        }
    }
    flavorDimensions 'basic'
    productFlavors {
        ads {
            applicationIdSuffix ".ads"
            resValue  'bool', 'includeMapping', 'false'
            resValue 'string', 'app_name', "WSJT-X "+buildString
        }
        noads {
            applicationIdSuffix ".noads"
            resValue  'bool', 'includeMapping', 'true'
            resValue 'string', 'app_name', "WSJT-X "+buildString+" Pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.feotec.wsjt_xmonitor'
    lint {
        warningsAsErrors true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    noadsImplementation 'com.google.android.gms:play-services-maps:19.2.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "androidx.preference:preference:1.2.1"
    androidTestImplementation 'androidx.test:rules:1.7.0'
    implementation 'androidx.work:work-runtime-ktx:2.10.4'       //  got PendingIntent.FLAG_IMMUTABLE error even though added the flag (UDPService.getNotification().  This seems to have fixed it on Android 12 API 31
}
